export const aboutIntro =
  "Founded in 1985, Creative Interiors has over the years established itself as one of the most trustworthy design studios in Mumbai. We are known for our unique approach, to architecture and interior design, which is a bespoke and very intimate process of discovering each client's personal style.";

export const aboutPara = [
  "Over the past few decades, Creative Interiors has emerged as a leading full-service Architecture, Interior Design and Décor firm based in Mumbai and have been working across the city on projects including commercial & residential projects.",
  "We constantly strive to create projects that stand out because of our distinct approach towards design, detail and the latest technology. Our design philosophy is to create authentic timeless designs, which inspire everyday basis life. We aim to create spaces that reflect your style and personality, giving justice to the design process, timelines & budget.",
  "Creative Interiors, formerly known as Rana Interiors, was established in 1985 by Late Mr Bansilal S. Rana, a self-motivated carpenter who started this business with lots of passion and a purpose. The purpose was to set up a design practice that has a process-oriented approach to design. Our team ensures that the design solution provided generates an environment that surpasses trends and fads by offering a more enriching spatial experience. We started as a small three-person team and have now grown to a team of over xx members.",
  "Currently, we operate a fully equipped furniture workshop dedicated to manufacturing furniture based on designs provided by architects or client specifications. Our workshop boasts state-of-the-art machinery, ensuring the highest quality and precision in every piece we create.",
  "We entered the interior design industry and established our own workshop equipped with dedicated, specialized machinery and skilled labor. Over time, we've successfully completed numerous interior turnkey projects, including residential, commercial, restaurants, shops, and more.",
];
